"""empty message

Revision ID: 0914f4fcf643
Revises: f9a7e47d5958
Create Date: 2022-05-16 14:17:25.794770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0914f4fcf643'
down_revision = 'f9a7e47d5958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stash', sa.Column('units_stashed', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stash', 'units_stashed')
    # ### end Alembic commands ###
