"""empty message

Revision ID: 32cc7440253e
Revises: 928c50dbb542
Create Date: 2022-05-03 10:05:41.728662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32cc7440253e'
down_revision = '928c50dbb542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('finished_weight', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('weight_unit', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'weight_unit')
    op.drop_column('projects', 'finished_weight')
    # ### end Alembic commands ###
