"""empty message

Revision ID: 34496c523398
Revises: 383827cc0eb0
Create Date: 2022-05-02 14:06:28.843699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34496c523398'
down_revision = '383827cc0eb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'draft_image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('draft_image_url', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
