"""empty message

Revision ID: 383827cc0eb0
Revises: 4cbbf9ba1190
Create Date: 2022-05-02 12:57:09.166928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383827cc0eb0'
down_revision = '4cbbf9ba1190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('warp_yarn', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('weft_yarn', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('epi', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('total_ends', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('ppi', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('draft_image_url', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('draft_notes', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('width_in_reed', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('length', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('finished_length', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'finished_length')
    op.drop_column('projects', 'length')
    op.drop_column('projects', 'width_in_reed')
    op.drop_column('projects', 'draft_notes')
    op.drop_column('projects', 'draft_image_url')
    op.drop_column('projects', 'ppi')
    op.drop_column('projects', 'total_ends')
    op.drop_column('projects', 'epi')
    op.drop_column('projects', 'weft_yarn')
    op.drop_column('projects', 'warp_yarn')
    # ### end Alembic commands ###
