"""empty message

Revision ID: 3fd68c9e6edc
Revises: 7f9a7d24cd69
Create Date: 2022-04-20 13:39:10.635003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd68c9e6edc'
down_revision = '7f9a7d24cd69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stash', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('stash', sa.Column('attributes', sa.Text(), nullable=True))
    op.add_column('stash', sa.Column('stored_in', sa.Text(), nullable=True))
    op.add_column('stash', sa.Column('fabric_width', sa.Integer(), nullable=True))
    op.add_column('stash', sa.Column('fabric_width_unit', sa.String(length=2), nullable=True))
    op.add_column('stash', sa.Column('fabric_weight', sa.Float(), nullable=True))
    op.add_column('stash', sa.Column('fabric_weight_unit', sa.String(length=2), nullable=True))
    op.add_column('stash', sa.Column('fabric_weight_area_unit', sa.String(length=2), nullable=True))
    op.add_column('stash', sa.Column('fabric_pattern_repeat_width', sa.Float(), nullable=True))
    op.add_column('stash', sa.Column('fabric_pattern_repeat_height', sa.Float(), nullable=True))
    op.add_column('stash', sa.Column('fabric_pattern_repeat_unit', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stash', 'fabric_pattern_repeat_unit')
    op.drop_column('stash', 'fabric_pattern_repeat_height')
    op.drop_column('stash', 'fabric_pattern_repeat_width')
    op.drop_column('stash', 'fabric_weight_area_unit')
    op.drop_column('stash', 'fabric_weight_unit')
    op.drop_column('stash', 'fabric_weight')
    op.drop_column('stash', 'fabric_width_unit')
    op.drop_column('stash', 'fabric_width')
    op.drop_column('stash', 'stored_in')
    op.drop_column('stash', 'attributes')
    op.drop_column('stash', 'tags')
    # ### end Alembic commands ###
