"""empty message

Revision ID: 5a1832650d15
Revises: 
Create Date: 2022-04-15 10:35:28.395466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a1832650d15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('profile_pic_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('pronouns_she', sa.Boolean(), nullable=False),
    sa.Column('pronouns_he', sa.Boolean(), nullable=False),
    sa.Column('pronouns_they', sa.Boolean(), nullable=False),
    sa.Column('pronouns_custom', sa.String(length=30), nullable=True),
    sa.Column('instagram', sa.String(length=30), nullable=True),
    sa.Column('twitter', sa.String(length=50), nullable=True),
    sa.Column('kofi', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('is_spinner', sa.Boolean(), nullable=False),
    sa.Column('is_weaver', sa.Boolean(), nullable=False),
    sa.Column('is_knitter', sa.Boolean(), nullable=False),
    sa.Column('is_crocheter', sa.Boolean(), nullable=False),
    sa.Column('is_sewist', sa.Boolean(), nullable=False),
    sa.Column('is_embroiderer', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('gallery_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('craft_types', sa.String(length=50), nullable=True),
    sa.Column('pattern_name', sa.String(length=100), nullable=True),
    sa.Column('pattern_author', sa.String(length=500), nullable=True),
    sa.Column('link_to_pattern', sa.Text(), nullable=True),
    sa.Column('size_made', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('attributes', sa.Text(), nullable=True),
    sa.Column('stored_in', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('yarn_weight', sa.String(length=20), nullable=True),
    sa.Column('grist', sa.Float(), nullable=True),
    sa.Column('grist_unit', sa.String(length=5), nullable=True),
    sa.Column('wpi', sa.Integer(), nullable=True),
    sa.Column('plies_count', sa.Integer(), nullable=True),
    sa.Column('twist_direction_singles', sa.String(length=1), nullable=True),
    sa.Column('twist_direction_plied', sa.String(length=1), nullable=True),
    sa.Column('twist_angle', sa.Float(), nullable=True),
    sa.Column('drive_ratio_singles', sa.Integer(), nullable=True),
    sa.Column('drive_ratio_plied', sa.Integer(), nullable=True),
    sa.Column('needle_sizes', sa.Text(), nullable=True),
    sa.Column('gauge_count', sa.Integer(), nullable=True),
    sa.Column('gauge_unit', sa.String(length=4), nullable=True),
    sa.Column('gauge_rows', sa.Integer(), nullable=True),
    sa.Column('gauge_size', sa.Integer(), nullable=True),
    sa.Column('gauge_size_unit', sa.String(length=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('acquired', sa.DateTime(), nullable=True),
    sa.Column('acquired_from', sa.Text(), nullable=True),
    sa.Column('acquired_price', sa.Float(), nullable=True),
    sa.Column('acquired_currency', sa.String(length=5), nullable=True),
    sa.Column('colors', sa.Text(), nullable=True),
    sa.Column('dyer_name', sa.Text(), nullable=True),
    sa.Column('colorway_name', sa.Text(), nullable=True),
    sa.Column('fiber_content', sa.String(length=200), nullable=True),
    sa.Column('fiber_quantity', sa.Float(), nullable=True),
    sa.Column('fiber_quantity_unit', sa.String(length=5), nullable=True),
    sa.Column('yarn_weight', sa.String(length=20), nullable=True),
    sa.Column('length_per_skein', sa.Float(), nullable=True),
    sa.Column('length_unit', sa.String(length=5), nullable=True),
    sa.Column('weight_per_skein', sa.Float(), nullable=True),
    sa.Column('weight_unit', sa.String(length=5), nullable=True),
    sa.Column('skeins_stashed', sa.Float(), nullable=True),
    sa.Column('length_stashed', sa.Float(), nullable=True),
    sa.Column('weight_stashed', sa.Float(), nullable=True),
    sa.Column('is_handspun', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('acquired', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('favorited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('for_spinning', sa.Boolean(), nullable=False),
    sa.Column('for_weaving', sa.Boolean(), nullable=False),
    sa.Column('for_knitting', sa.Boolean(), nullable=False),
    sa.Column('for_crocheting', sa.Boolean(), nullable=False),
    sa.Column('for_sewing', sa.Boolean(), nullable=False),
    sa.Column('for_embroidery', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('stash_id', sa.Integer(), nullable=True),
    sa.Column('fiber_quantity_used', sa.Float(), nullable=True),
    sa.Column('fiber_quantity_unit', sa.String(length=5), nullable=True),
    sa.Column('length_used', sa.Float(), nullable=True),
    sa.Column('length_unit', sa.String(length=5), nullable=True),
    sa.Column('skeins_used', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['stash_id'], ['stash.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('tool_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stash_item_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stash_item_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['stash_item_id'], ['stash.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stash_item_images')
    op.drop_table('project_tools')
    op.drop_table('project_materials')
    op.drop_table('project_images')
    op.drop_table('tools')
    op.drop_table('stash')
    op.drop_table('projects')
    op.drop_table('gallery_photos')
    op.drop_table('users')
    # ### end Alembic commands ###
