"""empty message

Revision ID: 5d2fbd38fd96
Revises: 9b3043a7570b
Create Date: 2022-05-04 12:22:44.547173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d2fbd38fd96'
down_revision = '9b3043a7570b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('finished_yarn_length', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('finished_yarn_length_unit', sa.String(length=2), nullable=True))
    op.add_column('projects', sa.Column('finished_yarn_weight', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('finished_yarn_weight_unit', sa.String(length=2), nullable=True))
    op.drop_column('projects', 'finished_weight')
    op.drop_column('projects', 'weight_unit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('weight_unit', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('finished_weight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('projects', 'finished_yarn_weight_unit')
    op.drop_column('projects', 'finished_yarn_weight')
    op.drop_column('projects', 'finished_yarn_length_unit')
    op.drop_column('projects', 'finished_yarn_length')
    # ### end Alembic commands ###
