"""empty message

Revision ID: 85d9ebe15f07
Revises: f3a743ac6662
Create Date: 2022-05-03 10:53:27.409290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d9ebe15f07'
down_revision = 'f3a743ac6662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('width_unit', sa.String(length=2), nullable=True))
    op.add_column('projects', sa.Column('finished_width', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'finished_width')
    op.drop_column('projects', 'width_unit')
    # ### end Alembic commands ###
