"""empty message

Revision ID: 928c50dbb542
Revises: 34496c523398
Create Date: 2022-05-02 14:13:25.121329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928c50dbb542'
down_revision = '34496c523398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('length_unit', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'length_unit')
    # ### end Alembic commands ###
