"""empty message

Revision ID: aa62f8366190
Revises: 0914f4fcf643
Create Date: 2022-05-17 11:45:51.098094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa62f8366190'
down_revision = '0914f4fcf643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_materials', sa.Column('units_used', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_materials', 'units_used')
    # ### end Alembic commands ###
