"""empty message

Revision ID: b60b2c33886c
Revises: 5d2fbd38fd96
Create Date: 2022-05-04 14:13:34.233707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b60b2c33886c'
down_revision = '5d2fbd38fd96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('knit_gauge_count', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('knit_gauge_unit', sa.String(length=4), nullable=True))
    op.add_column('projects', sa.Column('knit_gauge_rows', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('knit_gauge_size_width', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('knit_gauge_size_height', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('knit_gauge_size_unit', sa.String(length=2), nullable=True))
    op.add_column('projects', sa.Column('hook_sizes', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('crochet_gauge_count', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('crochet_gauge_unit', sa.String(length=4), nullable=True))
    op.add_column('projects', sa.Column('crochet_gauge_rows', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('crochet_gauge_size_width', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('crochet_gauge_size_height', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('crochet_gauge_size_unit', sa.String(length=2), nullable=True))
    op.drop_column('projects', 'gauge_count')
    op.drop_column('projects', 'gauge_size_width')
    op.drop_column('projects', 'gauge_unit')
    op.drop_column('projects', 'gauge_rows')
    op.drop_column('projects', 'gauge_size_height')
    op.drop_column('projects', 'gauge_size_unit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('gauge_size_unit', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('gauge_size_height', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('gauge_rows', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('gauge_unit', sa.VARCHAR(length=4), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('gauge_size_width', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('gauge_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('projects', 'crochet_gauge_size_unit')
    op.drop_column('projects', 'crochet_gauge_size_height')
    op.drop_column('projects', 'crochet_gauge_size_width')
    op.drop_column('projects', 'crochet_gauge_rows')
    op.drop_column('projects', 'crochet_gauge_unit')
    op.drop_column('projects', 'crochet_gauge_count')
    op.drop_column('projects', 'hook_sizes')
    op.drop_column('projects', 'knit_gauge_size_unit')
    op.drop_column('projects', 'knit_gauge_size_height')
    op.drop_column('projects', 'knit_gauge_size_width')
    op.drop_column('projects', 'knit_gauge_rows')
    op.drop_column('projects', 'knit_gauge_unit')
    op.drop_column('projects', 'knit_gauge_count')
    # ### end Alembic commands ###
