"""empty message

Revision ID: d4bed2e4bfe2
Revises: 5a1832650d15
Create Date: 2022-04-15 10:41:15.429014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4bed2e4bfe2'
down_revision = '5a1832650d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('gauge_size_width', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('gauge_size_height', sa.Integer(), nullable=True))
    op.drop_column('projects', 'gauge_size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('gauge_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('projects', 'gauge_size_height')
    op.drop_column('projects', 'gauge_size_width')
    # ### end Alembic commands ###
