"""empty message

Revision ID: dfd8cb52356b
Revises: b60b2c33886c
Create Date: 2022-05-16 11:30:34.604221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd8cb52356b'
down_revision = 'b60b2c33886c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stash', sa.Column('plies', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stash', 'plies')
    # ### end Alembic commands ###
