"""empty message

Revision ID: f3a743ac6662
Revises: 32cc7440253e
Create Date: 2022-05-03 10:49:53.561064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a743ac6662'
down_revision = '32cc7440253e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('warped_length', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'warped_length')
    # ### end Alembic commands ###
